# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, filepath, mtl }:

cabal.mkDerivation (self: {
  pname = "cached-traversable";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [ binary filepath mtl ];
  meta = {
    description = "Transparent, persistent caching of lazy, traversable structures";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
